feat: timecode countdown
bitfocus/companion-module-bmd-hyperdeck pull request #33
Opened 2021-02-16 21:58 UTC by baltedewit

This PR contains the following changes:
 * Query Hyperdeck for clips to be used in countdowns
 * Optionally use the new display timecode notifications from the hyperdeck instead of polling
 * Countdown timecode variables (Fixes https://github.com/bitfocus/companion-module-bmd-hyperdeck/issues/32)
 * Moved variables code into it's own file for clarity
 * Don't re-initiate all variables on timecode update, only update them

I think this is in a pretty good state I just need to figure what the right time is to rerun the query for clips but this is certainly ready for some testing and review. Once testing is done I'll coordinate a release of hyperdeck-connection as well.

2021-02-18 12:23 UTC, JeffreyDavidsz commented
@baltedewit you want me to merge? Or you want to wait for @sphlabs ?

2021-02-18 12:47 UTC, sphlabs commented
I’m hoping to test this over the next day or so.

> On 18 Feb 2021, at 12:23, Jeffrey Davidsz <notifications@github.com> wrote:
> 
> 
> @baltedewit <https://github.com/baltedewit> you want me to merge? Or you want to wait for @sphlabs <https://github.com/sphlabs> ?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/bitfocus/companion-module-bmd-hyperdeck/pull/33#issuecomment-781306590>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ALD6KYLD3Y4NNRJPQGZBFUDS7UBFVANCNFSM4XXGYUDA>.
>

2021-02-18 13:45 UTC, baltedewit commented
@JeffreyDavidsz I would like to wait a bit for some testing and maybe a review (which you are more than welcome to provide as well if you want). I believe I already have the access required to merge it after that but if not I'll give you or @sphlabs a ping.

2021-02-19 12:52 UTC, sphlabs requested changes
This looks really promising and the countdown timer generally works well.

There are a few specific timecode issues that need addressing, and one broader issue.

Since we are now making use of protocol 1.11 commands, we need to interrogate what version the deck is using, upon connection, and filter the available commands based on that. We cannot for instance assume that a HyperDeck Mini is running 1.11 as it may not have been updated.

So the countdown features become a subset of making the module support both 1.8 and 1.11. I am happy to look at this.

Some specific points on the timecode countdown:
- It is currently possible to select Timecode Notifications for a device that does not support it, which causes connection to the deck to fail and/or cause crashes.
- I can't think of a situation where one would want/need both timecode notifications and polling, so selecting both should be prevented.
- as noted in the code, we can't make an assumption of frame rate, if that information is not available.
- I saw some odd countdown values as the deck played through from one clip to the next, but that is a less critical edge case.

So I think that we need to update the module to properly support the 1.11 protocol (which seems to have various small incompatibilities with the way 1.8 worked anyway) will be needed before we can bring in this update.

Unless you want to take out the notification support and push through an update that just uses polling for now?

2021-02-19 12:52 UTC, sphlabs commented on variables.js
> +    const tb = frameRates[instance.transportInfo['video format']] || 25
The variable should be `transportInfo['videoFormat']`. However, there shouldn't be a default assumption of 25 fps, as that will cause a fatal crash for any timecode values of 25+ frames.

If `videoFormat` for the clip is not available, for whatever reason, then the behaviour should be to pass through (count up) timecode, and to not calculate/display countdown timecode.

2021-02-19 14:29 UTC, baltedewit commented on variables.js
> +    const tb = frameRates[instance.transportInfo['video format']] || 25
I had not expected a fatal crash there, it's a shame the library doesn't handle that better. Disabling countdowns sound like a good option because it implies we don't know the format of the deck anyway so it would only be correct by luck.

2021-02-19 14:32 UTC, sphlabs commented on variables.js
> +    const tb = frameRates[instance.transportInfo['video format']] || 25
Agreed. I don't know why we wouldn't know the frame rate, but if we don't then obviously can't do the maths correctly.

2021-02-19 14:41 UTC, baltedewit commented
I have admittedly been a bit lazy with ignoring version checks and letting it up to the user to enable the right things for their deck, I did add the clarification to the configuration but who reads those anyway, right?

I have personally not seen anything that is a breaking change in the protocol thankfully, only additions of which I then only used the timecode notifications. If you see anything that should be handled in `hyperdeck-connection` please let me know! Otherwise I think a simple version check (string comparison might even be sufficient?) for the initial `notify` command should be sufficient for this PR.

I will have to play around a bit more with playing back to back clips as it seemed OK when I did it.

2021-02-21 07:37 UTC, JeffreyDavidsz commented
Guys query'n the hyperdeck for clips; would it be possible to fetch the order on which they are and put them for example in a dropdown to select? This option would be very handy for hyperdecks mini for example where you upload files but don't know on which order hyperdeck is putting them

2021-02-21 11:50 UTC, baltedewit commented
> would it be possible to fetch the order on which they are and put them for example in a dropdown to select

Sort of, the order might change as the hyperdeck maintains an internal playlist and I'm not sure what the logic is behind the ordering. So it might be that when you upload you get a certain order and then restart and you get a different one. Besides that the dropdown would have to have some awareness of slots as the same clip id can have different clips depending on the slot. To complicate things even more, you can change the file format of the deck and get completely different clips. To conclude: I think it's a good feature to have but big enough to warrant it's own PR.

2021-02-28 21:43 UTC, sphlabs reviewed
Looking good. The crashes I was getting are all fixed now, although I only have a Hyperdeck Studio at home, so can't actually test the notifications option at the moment.

Just a couple of suggested code changes, I've noted inline.

I wonder about actively removing 'notifications' as a option if the deck isn't running v1.11, although that might be a bit too hand-holdy…? We do allow people to override the deck type after all.

2021-02-28 21:43 UTC, sphlabs commented on index.js
> +			}
This would be clearer to read as:
```
if (config.timecodeVariables === 'notification') {
  ...
  notify.displayTimecode = true
  ...
} else {
  ...
  notify.displayTimecode = false
  ...
}
```

2021-02-28 21:43 UTC, sphlabs commented on index.js
> +					{ id: 'polling', label: 'Polling' },
These should be defined in the contstructor, as something like `this.CONFIG_TIMECODEMETHOD`

2021-03-05 11:08 UTC, sphlabs commented on index.js
> +			}
although, on reflection, I can see that your method does save the sending of some superfluous commands.

2021-03-06 14:10 UTC, baltedewit commented on index.js
> +			}
I'll clarify with some comments as the logic in your version isn't _quite_ the same

2021-03-06 14:16 UTC, baltedewit commented
@sphlabs I've pushed an update for the last of your comments so if you agree I'd like to merge this in now

2021-03-06 18:46 UTC, sphlabs approved these changes

2021-03-06 18:49 UTC, merged